version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/fabric-peer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/docker/fabric-tools"
    schedule:
      interval: "monthly"
