apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: substra/fabric-tools
    context: .
    docker:
      dockerfile: docker/fabric-tools/Dockerfile
  - image: substra/fabric-peer
    context: .
    docker:
      dockerfile: docker/fabric-peer/Dockerfile
manifests:
  rawYaml:
  - examples/secrets/secrets-orderer-genesis.yaml
  - examples/secrets/secrets-orderer.yaml
  - examples/secrets/secrets-org-1.yaml
  - examples/secrets/secrets-org-2.yaml
  - examples/serviceAccounts/serviceAccount-org-1.yaml
  - examples/serviceAccounts/serviceAccount-org-2.yaml
  helm:
    releases:
    - name: network-orderer
      chartPath: charts/hlf-k8s
      valuesFiles:
      - examples/2-orgs-policy-any-no-ca/values/orderer.yaml
      namespace: orderer
      setValueTemplates:
        fabric-tools.image.repository: '{{.IMAGE_REPO_substra_fabric_tools}}'
        fabric-tools.image.tag: '{{.IMAGE_TAG_substra_fabric_tools}}@{{.IMAGE_DIGEST_substra_fabric_tools}}'
      createNamespace: true
    - name: network-org-1-peer-1
      chartPath: charts/hlf-k8s
      valuesFiles:
      - examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
      namespace: org-1
      setValueTemplates:
        fabric-tools.image.repository: '{{.IMAGE_REPO_substra_fabric_tools}}'
        fabric-tools.image.tag: '{{.IMAGE_TAG_substra_fabric_tools}}@{{.IMAGE_DIGEST_substra_fabric_tools}}'
        hlf-peer.image.repository: '{{.IMAGE_REPO_substra_fabric_peer}}'
        hlf-peer.image.tag: '{{.IMAGE_TAG_substra_fabric_peer}}@{{.IMAGE_DIGEST_substra_fabric_peer}}'
      createNamespace: true
      skipBuildDependencies: true
    - name: network-org-2-peer-1
      chartPath: charts/hlf-k8s
      valuesFiles:
      - examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
      namespace: org-2
      setValueTemplates:
        fabric-tools.image.repository: '{{.IMAGE_REPO_substra_fabric_tools}}'
        fabric-tools.image.tag: '{{.IMAGE_TAG_substra_fabric_tools}}@{{.IMAGE_DIGEST_substra_fabric_tools}}'
        hlf-peer.image.repository: '{{.IMAGE_REPO_substra_fabric_peer}}'
        hlf-peer.image.tag: '{{.IMAGE_TAG_substra_fabric_peer}}@{{.IMAGE_DIGEST_substra_fabric_peer}}'
      createNamespace: true
      skipBuildDependencies: true
deploy:
  helm: {}
  kubectl: {}
  statusCheckDeadlineSeconds: 300
profiles:
- name: nodeps
  patches:
  - op: add
    path: /manifests/helm/releases/0/skipBuildDependencies
    value: true
- name: single-org
  patches:
  - op: remove
    path: /manifests/helm/releases/2
    # Removes the org-2 manifests, at indexes 3 and 5.
    # we remove index 5 first because starting with index 3 turns index 5 into index 4 and that's
    # confusing.
  - op: remove
    path: /manifests/rawYaml/manifests/5
  - op: remove
    path: /manifests/rawYaml/manifests/3
