# Copyright 2018 Owkin, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: substra/fabric-tools
      context: ../../
      docker:
        dockerfile: docker/fabric-tools/Dockerfile

    - image: substra/fabric-peer
      context: ../../
      docker:
        dockerfile: docker/fabric-peer/Dockerfile

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: network-orderer
        chartPath: ../../charts/hlf-k8s
        namespace: orderer
        createNamespace: true
        valuesFiles: [values/orderer.yaml]
        imageStrategy:
          helm: {}
        artifactOverrides:
          fabric-tools.image: substra/fabric-tools

      - name: network-org-1-peer-1
        chartPath: ../../charts/hlf-k8s
        namespace: org-1
        createNamespace: true
        valuesFiles: [values/org-1-peer-1.yaml]
        imageStrategy:
          helm: {}
        artifactOverrides:
          fabric-tools.image: substra/fabric-tools
          hlf-peer.image: substra/fabric-peer

      - name: network-org-2-peer-1
        chartPath: ../../charts/hlf-k8s
        namespace: org-2
        createNamespace: true
        valuesFiles: [values/org-2-peer-1.yaml]
        imageStrategy:
          helm: {}
        artifactOverrides:
          fabric-tools.image: substra/fabric-tools
          hlf-peer.image: substra/fabric-peer

  kubectl:
    manifests:
      - ../secrets/secrets-orderer-genesis.yaml
      - ../secrets/secrets-orderer.yaml
      - ../secrets/secrets-org-1.yaml
      - ../secrets/secrets-org-2.yaml
      # For chaincode secrets deletion
      - ../serviceAccounts/serviceAccount-org-1.yaml
      - ../serviceAccounts/serviceAccount-org-2.yaml

