@startuml

skinparam shadowing false


package "Node B" as nodeB {
   rectangle "peer" as peerB {
    database ledgerB [
      ledger
      ----
      ----
    ]
  }
  rectangle "substrabac" as substrabacB {
    database localdbB [
      local db
      ----
      ----
    ]
    node server as djangoB
  }
  rectangle "Fabric CA" as fcaB {
    rectangle db as fcadbB {
        database usersB [
            users
            ----
            ----
        ]
        file {
            card USER_B
            card NODE_B_USER_A
            card NODE_B_USER_A1 #PHYSICAL
        }
    }
    node server as fcaserverB
  }
}

actor "client from Node A\n(which is <b>NODE_B_USER_A1</b>)" as client

USER_B -[hidden]r- NODE_B_USER_A
NODE_B_USER_A -[hidden]r- NODE_B_USER_A1

fcaserverB <-[#orange]> usersB

client .> djangoB: " " "<font color=red><b>1. credentials in cookies</b></font>"

djangoB .> ledgerB: <font color=red>2. get asset permissions</font>
djangoB <.[#green]. ledgerB

djangoB .> fcaserverB: " " "<font color=red>4. enroll</font>"
djangoB <.[#green]. fcaserverB

djangoB .> djangoB: \n\n\n\n\n\n<font color="red">3. if permission not all</font>\n<font color="red">enroll with credentials</font>\n<font color="red">5. check asset permissions</font>\n<font color="red">on Internal User with right</font>\n<font color="red">modulus and permission</font>

djangoB <-[#orange]> localdbB: 6. get object

client <.[#green]. djangoB: 7. return file content or raise error




@enduml
