apiVersion: v1
items:
- apiVersion: v1
  data:
    cacert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNLVENDQWMrZ0F3SUJBZ0lVUm5RWXpnNk5xcldFSTJzRlVpQUNZUTlWM1lJd0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUTTNNREl5TkRFM05UY3cKTUZvd2NURUxNQWtHQTFVRUJoTUNSbEl4R1RBWEJnTlZCQWdURUV4dmFYSmxMVUYwYkdGdWRHbHhkV1V4RHpBTgpCZ05WQkFjVEJrNWhiblJsY3pFUU1BNEdBMVVFQ2hNSFUzVmljM1J5WVRFUE1BMEdBMVVFQ3hNR1JtRmljbWxqCk1STXdFUVlEVlFRREV3cHlZMkZQY21SbGNtVnlNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUKSUdUNnc3OS9oZ2JScVdVcU9OemU0WnRuY3BvWmdXTGZMSXFmUUF2dUp3ZUtCSnhCaUdOSGxISWZXVStKWExXcAo5Tk1Dcno3VVZUY2J3MDVsVDJpcy9hTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJCk1BWUJBZjhDQVFFd0hRWURWUjBPQkJZRUZIU2JQNUNzU1R2MmdkN3MrYXBuWDFiK2RWWm9NQW9HQ0NxR1NNNDkKQkFNQ0EwZ0FNRVVDSVFEenNJRlJXQTdYd1MwMnNjdGZKNTVvWjNoeGRuMHpSZWMyOThROTdoOStMQUlnSitlUwpVemwzcFR5RFRJOHlMeG55VTRnWUpvZVNobmJPbWhuaWRDR2VzMGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:10Z"
    name: hlf-cacert
    namespace: orderer
    resourceVersion: "1156765"
    uid: b7891bef-28dd-46ba-ae1d-b088ed4cdbe7
  type: Opaque
- apiVersion: v1
  data:
    cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1VENDQW95Z0F3SUJBZ0lVVDZKNUwxL2JYYklnQXV1cGY5bHR5dnpWNmljd0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUSTNNREl5TnpFNE1ETXcKTUZvd1hURUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGs1dmNuUm9JRU5oY205c2FXNWhNUlF3RWdZRApWUVFLRXd0SWVYQmxjbXhsWkdkbGNqRVBNQTBHQTFVRUN4TUdZMnhwWlc1ME1RNHdEQVlEVlFRREV3VmhaRzFwCmJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLaW0zb2JNR1paUlRzV1JhZmRObjJMblVrMnAKNUJ4YkJiTjVYU3NOdnRKQU1YR2dWRnFuV0JlU2NQQ3RXaVpLNEtvTGtvR2pFcVJWTG8zOTdPTFhyU2VqZ2dFVQpNSUlCRURBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVrTzBaCm9IdmNPRWxacnRkWXVtV0YrSXNHRjRJd0h3WURWUjBqQkJnd0ZvQVVkSnMva0t4Sk8vYUIzdXo1cW1kZlZ2NTEKVm1nd1J3WURWUjBSQkVBd1BvSThibVYwZDI5eWF5MXZjbVJsY21WeUxXaHNaaTFyT0hNdFpXNXliMnhzYldWdQpkQzF2Y0dWeVlYUnZjaTAzWTJRMU56azFaamhpTFRaM2F6bG5NR2NHQ0NvREJBVUdCd2dCQkZ0N0ltRjBkSEp6CklqcDdJbUZrYldsdUlqb2lkSEoxWlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHMKYldWdWRFbEVJam9pWVdSdGFXNGlMQ0pvWmk1VWVYQmxJam9pWTJ4cFpXNTBJbjE5TUFvR0NDcUdTTTQ5QkFNQwpBMGNBTUVRQ0lIbWxtWWNtZ3M4RHlpNmRYR2NINkJiSCsrNkxIbXlDTURRdjk3aW9URXo0QWlBK2h6QjRzSjVXCnJ1WEtjSGRkaTE1UHZNN2x4bEF5UTY0ZmEyQkRkdm5VWHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:16Z"
    name: hlf-msp-cert-admin
    namespace: orderer
    resourceVersion: "1156811"
    uid: 9e86a3e8-6ffd-4516-9386-afc694ac98ad
  type: Opaque
- apiVersion: v1
  data:
    cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxekNDQW4yZ0F3SUJBZ0lVUzdMN1ZkRDlCeW1jZHBjbDRjeGVDUHpHcVdZd0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUSTNNREl5TnpFNE1ETXcKTUZvd1hURUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGs1dmNuUm9JRU5oY205c2FXNWhNUlF3RWdZRApWUVFLRXd0SWVYQmxjbXhsWkdkbGNqRVFNQTRHQTFVRUN4TUhiM0prWlhKbGNqRU5NQXNHQTFVRUF4TUVkWE5sCmNqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCZ0xGK2g2TEY2d2ZLYWlyV0l3b0RDWTB1WmcKR1RtUTFYYVRYYjVldFFFWlU0SG05RE5NS2RNUHd4MlI5Q0xmZ3VpeW4vRUJLN2hraEM5Z3V2ZGZlMWFqZ2dFRgpNSUlCQVRBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVMaDM3ClpDcWRZMDFxYVpvMkFiaUlGR09VQnNnd0h3WURWUjBqQkJnd0ZvQVVkSnMva0t4Sk8vYUIzdXo1cW1kZlZ2NTEKVm1nd1J3WURWUjBSQkVBd1BvSThibVYwZDI5eWF5MXZjbVJsY21WeUxXaHNaaTFyT0hNdFpXNXliMnhzYldWdQpkQzF2Y0dWeVlYUnZjaTAzWTJRMU56azFaamhpTFRaM2F6bG5NRmdHQ0NvREJBVUdCd2dCQkV4N0ltRjBkSEp6CklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pZFhObGNpSXMKSW1obUxsUjVjR1VpT2lKdmNtUmxjbVZ5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ1J3VGVhdnlDdgpwNmpMRDF6OVBGRXFaaFA1blJnZmxqQk5zbjNxRFR3Zm5RSWdEQTBuUGIxeGY0NVlIcUVTTFNweHRLMWVTYSs5CmdmOUxNL0JFSEhwaE1Fbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:23Z"
    name: hlf-msp-cert-user
    namespace: orderer
    resourceVersion: "1156881"
    uid: eac3786c-cf98-4b09-8922-38930adb5c72
  type: Opaque
- apiVersion: v1
  data:
    key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ05LekwxcUtjM1JJMDM2WVIKTjlDT1UyREFYNVNkZWZlMUlWS2Z1U1NydGllaFJBTkNBQVNvcHQ2R3pCbVdVVTdGa1duM1RaOWk1MUpOcWVRYwpXd1d6ZVYwckRiN1NRREZ4b0ZSYXAxZ1hrbkR3clZvbVN1Q3FDNUtCb3hLa1ZTNk4vZXppMTYwbgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:17Z"
    name: hlf-msp-key-admin
    namespace: orderer
    resourceVersion: "1156821"
    uid: ff9bbcae-104f-42e7-b5c2-d67e7209721c
  type: Opaque
- apiVersion: v1
  data:
    key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0lhYm8wZlJSbkFEalB1L1MKNlJqb05VUHQzcXVBdGVBVjhpZjFTRHRNMkVxaFJBTkNBQVFZQ3hmb2VpeGVzSHltb3ExaU1LQXdtTkxtWUJrNQprTlYyazEyK1hyVUJHVk9CNXZRelRDblREOE1ka2ZRaTM0TG9zcC94QVN1NFpJUXZZTHIzWDN0VwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:25Z"
    name: hlf-msp-key-user
    namespace: orderer
    resourceVersion: "1156906"
    uid: 5414285f-8be8-4122-92fe-707410c73eb8
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQXJHZ0F3SUJBZ0lVRmZ5cnkyazlSR3FiZ3B5cmROQ29pWS9BYnZJd0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUSTNNREl5TnpFNE1ETXcKTUZvd1hURUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGs1dmNuUm9JRU5oY205c2FXNWhNUlF3RWdZRApWUVFLRXd0SWVYQmxjbXhsWkdkbGNqRVBNQTBHQTFVRUN4TUdZMnhwWlc1ME1RNHdEQVlEVlFRREV3VmhaRzFwCmJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCNERtS1BDVWtnZ0xuMG5FTFZMY1g3QVNwdVEKb3JDSE1uTUdETjF2VnpuWHpuL0pzbjJ1MldNcTNUYlJFWXh3WGpGTFdpYW0zQkhBdGgzUjNEeHJ4Y09qZ2dFNQpNSUlCTlRBT0JnTlZIUThCQWY4RUJBTUNBNmd3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGCkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZFR2hDNUtwN3BzMFE0U3k4bWc0WlZBZlZxRnMKTUI4R0ExVWRJd1FZTUJhQUZIU2JQNUNzU1R2MmdkN3MrYXBuWDFiK2RWWm9NRTBHQTFVZEVRUkdNRVNDQ1d4dgpZMkZzYUc5emRJSXhibVYwZDI5eWF5MXZjbVJsY21WeUxXaHNaaTF2Y21RdWIzSmtaWEpsY2k1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJY0Vmd0FBQVRCbkJnZ3FBd1FGQmdjSUFRUmJleUpoZEhSeWN5STZleUpoWkcxcGJpSTYKSW5SeWRXVWlMQ0pvWmk1QlptWnBiR2xoZEdsdmJpSTZJaUlzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SW1GawpiV2x1SWl3aWFHWXVWSGx3WlNJNkltTnNhV1Z1ZENKOWZUQUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEyTzNiCmRrNnFvemRkRDk1NlR6Nnk2ZWhUM29qR01oWFFwcWc3NzhIVkxoSUNJR05vT2Q0VzBwNTVkZFNBYlZOL2RzbngKTk5NNGZPOU1uS2xmamNFYTB2bU8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3dYSmdwNmV0clI4ZFFxQ2cKcEt6dkwzdTlvaXN6cThQMlJ5ZHdZVDBZY0lDaFJBTkNBQVFlQTVpandsSklJQzU5SnhDMVMzRit3RXFia0tLdwpoekp6Qmd6ZGIxYzUxODUveWJKOXJ0bGpLdDAyMFJHTWNGNHhTMW9tcHR3UndMWWQwZHc4YThYRAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:19Z"
    name: hlf-tls-admin
    namespace: orderer
    resourceVersion: "1156835"
    uid: fffafcb0-a972-4aa2-a369-748d8a3ca995
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQXFLZ0F3SUJBZ0lVSS9pejdtRkJHcFQvWG1DSURuNzN2cUpwSUY4d0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUSTNNREl5TnpFNE1ETXcKTUZvd1hURUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGs1dmNuUm9JRU5oY205c2FXNWhNUlF3RWdZRApWUVFLRXd0SWVYQmxjbXhsWkdkbGNqRVFNQTRHQTFVRUN4TUhiM0prWlhKbGNqRU5NQXNHQTFVRUF4TUVkWE5sCmNqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCWW1MeitNeWErNnlkcGl4VXgvV2paYUlaUkUKTm1JQnF3amJhNFE1dlZ6NWxlZWpxaFk4RS9kWTc5WlhxRHZVQy9MSExsM3luSnMwRFRwbG9FYjdpZmFqZ2dFcQpNSUlCSmpBT0JnTlZIUThCQWY4RUJBTUNBNmd3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGCkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZJRCtEZWhRVDJCTkF6eWVEU3IrV1JyYlNLTysKTUI4R0ExVWRJd1FZTUJhQUZIU2JQNUNzU1R2MmdkN3MrYXBuWDFiK2RWWm9NRTBHQTFVZEVRUkdNRVNDQ1d4dgpZMkZzYUc5emRJSXhibVYwZDI5eWF5MXZjbVJsY21WeUxXaHNaaTF2Y21RdWIzSmtaWEpsY2k1emRtTXVZMngxCmMzUmxjaTVzYjJOaGJJY0Vmd0FBQVRCWUJnZ3FBd1FGQmdjSUFRUk1leUpoZEhSeWN5STZleUpvWmk1QlptWnAKYkdsaGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNkluVnpaWElpTENKb1ppNVVlWEJsSWpvaQpiM0prWlhKbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUEyRXVIMndWWFBTNXNXNUVJZ01RNjVwclkxCk1veEVreXV6RHExeGhZOW9BUUlnYWJkUlBVcmhvdFJWY1pPZFhoNlU4cVBodW5TNWRUQkZEUENHL25PWUZYTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1hyZDU4bkdXa0puanNOdkMKQzJLaXZEb2pWRkxieCtyZ0h2Ri9zVmNuMVNpaFJBTkNBQVFXSmk4L2pNbXZ1c25hWXNWTWYxbzJXaUdVUkRaaQpBYXNJMjJ1RU9iMWMrWlhubzZvV1BCUDNXTy9XVjZnNzFBdnl4eTVkOHB5Yk5BMDZaYUJHKzRuMgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:26Z"
    name: hlf-tls-user
    namespace: orderer
    resourceVersion: "1156928"
    uid: 6ed4d80f-1abb-4158-b13f-6b2b6e3f8866
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    cacert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNLVENDQWMrZ0F3SUJBZ0lVUm5RWXpnNk5xcldFSTJzRlVpQUNZUTlWM1lJd0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUTTNNREl5TkRFM05UY3cKTUZvd2NURUxNQWtHQTFVRUJoTUNSbEl4R1RBWEJnTlZCQWdURUV4dmFYSmxMVUYwYkdGdWRHbHhkV1V4RHpBTgpCZ05WQkFjVEJrNWhiblJsY3pFUU1BNEdBMVVFQ2hNSFUzVmljM1J5WVRFUE1BMEdBMVVFQ3hNR1JtRmljbWxqCk1STXdFUVlEVlFRREV3cHlZMkZQY21SbGNtVnlNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUKSUdUNnc3OS9oZ2JScVdVcU9OemU0WnRuY3BvWmdXTGZMSXFmUUF2dUp3ZUtCSnhCaUdOSGxISWZXVStKWExXcAo5Tk1Dcno3VVZUY2J3MDVsVDJpcy9hTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJCk1BWUJBZjhDQVFFd0hRWURWUjBPQkJZRUZIU2JQNUNzU1R2MmdkN3MrYXBuWDFiK2RWWm9NQW9HQ0NxR1NNNDkKQkFNQ0EwZ0FNRVVDSVFEenNJRlJXQTdYd1MwMnNjdGZKNTVvWjNoeGRuMHpSZWMyOThROTdoOStMQUlnSitlUwpVemwzcFR5RFRJOHlMeG55VTRnWUpvZVNobmJPbWhuaWRDR2VzMGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:12Z"
    name: ord-tls-rootcert
    namespace: orderer
    resourceVersion: "1156774"
    uid: ca11f929-9431-414f-8136-d06dacb2b74c
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
