apiVersion: v1
items:
- apiVersion: v1
  data:
    cacert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJakNDQWNtZ0F3SUJBZ0lVRklHTHBIMHRhSnlUbXYrQVFqS3RjM1J6ZU4wd0NnWUlLb1pJemowRUF3SXcKYmpFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUkF3CkRnWURWUVFERXdkeVkyRlBjbWN4TUI0WERUSXlNREl5T0RFM05UZ3dNRm9YRFRNM01ESXlOREUzTlRnd01Gb3cKYmpFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUkF3CkRnWURWUVFERXdkeVkyRlBjbWN4TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUTdtL2phYjkKU04xVDRZb2NzU3owNy9PYWNvZDJXUnF3UTlKcVRLRHcwM0YvcVU1SGpycjREc0wxeDhaaTRMNFp3d1lWcEIzdQp1NHhyOVlQZE5UMkdZNk5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSU1BWUJBZjhDCkFRRXdIUVlEVlIwT0JCWUVGSkhXWDBhakpTMlhaRnVKRlkvOUZQcHJBc1ZMTUFvR0NDcUdTTTQ5QkFNQ0EwY0EKTUVRQ0lEclBZY0NudFVTN3VjRmVNWWxKZkExVWlyaGNnOWVhM094NndxZHBjWlczQWlBeVNud2czTFgxOHdKdAp3VGNQUXE5d2dYRTg4RlVMcGRlTW1pN0U0VisvRWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:31Z"
    name: hlf-cacert
    namespace: org-1
    resourceVersion: "1156980"
    uid: 6dc14d9f-fb21-4219-9ed1-b4f62a20b304
  type: Opaque
- apiVersion: v1
  data:
    cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQXArZ0F3SUJBZ0lVSGdNcC9Hamh4cmZXa2VHNW94THBDUTFEd21Vd0NnWUlLb1pJemowRUF3SXcKYmpFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUkF3CkRnWURWUVFERXdkeVkyRlBjbWN4TUI0WERUSXlNREl5T0RFM05UZ3dNRm9YRFRJM01ESXlOekU0TURRd01Gb3cKWFRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1kyeHBaVzUwTVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkc2RTZQN010RE0vS2thQVladE0zaVpDL3NvRk5MdDkKMkY3TnpCMGNxS1NhYWRIRmZNOHkwcXJnSTJZYzdYOFhIVUwyRjRETEpaU2dIdmdRdVNMS0tWaWpnZ0VxTUlJQgpKakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVUlodUVXM2VrCkZPM0YxaDFzRkxxeUQ5VGs2dVV3SHdZRFZSMGpCQmd3Rm9BVWtkWmZScU1sTFpka1c0a1ZqLzBVK21zQ3hVc3cKU2dZRFZSMFJCRU13UVlJL2JtVjBkMjl5YXkxdmNtY3RNUzF3WldWeUxURXRhR3htTFdzNGN5MWxibkp2Ykd4dApaVzUwTFc5d1pYSmhkRzl5TFRVMU56UmpaalkzWkRkdWFIQm9NSG9HQ0NvREJBVUdCd2dCQkc1N0ltRjBkSEp6CklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0poWkcxcGJpSTZJblJ5ZFdVaUxDSm9aaTVCWm1acGJHbGgKZEdsdmJpSTZJaUlzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SW1Ga2JXbHVJaXdpYUdZdVZIbHdaU0k2SW1OcwphV1Z1ZENKOWZUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQTdub2R4YldJTm53QktBUVBwdW1aV1ZSL1dYNGdvCjl3eExpdnd4dFdGd1BBSWdZc1BMSk9JaUJlZ01DLzVGUmZCWmZZOHNwRUtMOUhRV3JTamJXaXV5c2ZzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:37Z"
    name: hlf-msp-cert-admin
    namespace: org-1
    resourceVersion: "1157024"
    uid: b7f92aef-25db-4c36-abec-af1a0ef9bdc3
  type: Opaque
- apiVersion: v1
  data:
    cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQW5lZ0F3SUJBZ0lVVnlOUXBrVFovSUpmdFlxOG9YNm9iZkdQSkZRd0NnWUlLb1pJemowRUF3SXcKYmpFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUkF3CkRnWURWUVFERXdkeVkyRlBjbWN4TUI0WERUSXlNREl5T0RFM05UZ3dNRm9YRFRJM01ESXlOekU0TURRd01Gb3cKV2pFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFTk1Bc0dBMVVFQ3hNRWNHVmxjakVOTUFzR0ExVUVBeE1FZFhObGNqQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTHBSSFlmNVA1eDM5a2NIcm9GSHc1NHdsY25hREdyU0JPeisKOTd6Nm9admpydndqU2lxbFNZUGIxalVHelZTN1JNalZtUGVNb3JFNWkyOGdVNkdvOFNTamdnRUZNSUlCQVRBTwpCZ05WSFE4QkFmOEVCQU1DQjRBd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVQWxOVFBPZmpSbmtaCkdZN013MjIwNGZtYkxOZ3dId1lEVlIwakJCZ3dGb0FVa2RaZlJxTWxMWmRrVzRrVmovMFUrbXNDeFVzd1NnWUQKVlIwUkJFTXdRWUkvYm1WMGQyOXlheTF2Y21jdE1TMXdaV1Z5TFRFdGFHeG1MV3M0Y3kxbGJuSnZiR3h0Wlc1MApMVzl3WlhKaGRHOXlMVFUxTnpSalpqWTNaRGR1YUhCb01GVUdDQ29EQkFVR0J3Z0JCRWw3SW1GMGRISnpJanA3CkltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lkWE5sY2lJc0ltaG0KTGxSNWNHVWlPaUp3WldWeUluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJQW5Ec3RSMTNiWk9USEpOK01yMQpud1VteEtwQ2VVM1htTWxIUHcvbkRCdlRBaUFxMUlBN0xBd3hOdzRkWEg3WnphaFVkWWtzVlM4ZVBDN1ZveTF4ClZSNGNMdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:44Z"
    name: hlf-msp-cert-user
    namespace: org-1
    resourceVersion: "1157078"
    uid: 0fc4c5e0-0de6-46fa-a62b-72bd9c07d58c
  type: Opaque
- apiVersion: v1
  data:
    key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ280L2tKQW1wLzg2ZW94K2sKeHc5endqTnRpdEZvRXN3MCtNUzVPMWVlY1ZhaFJBTkNBQVJ1aE9qK3pMUXpQeXBHZ0dHYlRONG1RdjdLQlRTNwpmZGhlemN3ZEhLaWttbW5SeFh6UE10S3E0Q05tSE8xL0Z4MUM5aGVBeXlXVW9CNzRFTGtpeWlsWQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:38Z"
    name: hlf-msp-key-admin
    namespace: org-1
    resourceVersion: "1157033"
    uid: e291b653-44e2-4c07-b871-fe8dbbfd745a
  type: Opaque
- apiVersion: v1
  data:
    key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ09ZVlVjdVR4RmxrRXJKQVUKeWdtTGNROGYrVmpxRUpBeFRaNTUvMWpOL25haFJBTkNBQVM2VVIySCtUK2NkL1pIQjY2QlI4T2VNSlhKMmd4cQowZ1RzL3ZlOCtxR2I0Njc4STBvcXBVbUQyOVkxQnMxVXUwVEkxWmozaktLeE9ZdHZJRk9ocVBFawotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:45Z"
    name: hlf-msp-key-user
    namespace: org-1
    resourceVersion: "1157089"
    uid: efd2486b-6607-4277-8b93-d78a4c6a07f5
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBakNDQXFtZ0F3SUJBZ0lVQXlkcC83cDEyZkt0b292cHlVaDB0VmdrL3Rrd0NnWUlLb1pJemowRUF3SXcKYmpFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUkF3CkRnWURWUVFERXdkeVkyRlBjbWN4TUI0WERUSXlNREl5T0RFM05UZ3dNRm9YRFRJM01ESXlOekU0TURRd01Gb3cKWFRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1kyeHBaVzUwTVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkx6ejE1UHZTVm01Mml2LzBMNW1NY3BlbEdUUW51Z20KbXFySmx6eE1iS0lsUEh4ckUyOUdsMTF2dmhDNTNabFM3dzdkSGFkYzhPT2lmVjFSM1RsOUlWV2pnZ0UwTUlJQgpNREFPQmdOVkhROEJBZjhFQkFNQ0E2Z3dIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DCk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRlB2MlQrdzQ5cUMxMUs3cnRwZzlOVUxDRGszOU1COEcKQTFVZEl3UVlNQmFBRkpIV1gwYWpKUzJYWkZ1SkZZLzlGUHByQXNWTE1EVUdBMVVkRVFRdU1DeUNDV3h2WTJGcwphRzl6ZElJWktpNXZjbWN0TVM1emRtTXVZMngxYzNSbGNpNXNiMk5oYkljRWZ3QUFBVEI2QmdncUF3UUZCZ2NJCkFRUnVleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGlPaUowY25WbElpd2kKYUdZdVFXWm1hV3hwWVhScGIyNGlPaUlpTENKb1ppNUZibkp2Ykd4dFpXNTBTVVFpT2lKaFpHMXBiaUlzSW1obQpMbFI1Y0dVaU9pSmpiR2xsYm5RaWZYMHdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdKQmNzZWhJQW9UU20zaElLClBoc1JNL0srN3lGYkIwYVBzZ2ZwQmNmMTNDa0NJRWlkL2NVQk14TDlXYjk0WmhKRC9lTmp5NndFdnducDU5dzQKWkRkeUJrejYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1RoVW1jU0RrRjBSKzlUbUUKSjZxaCtRWTFpZ1ZHQ1ByVkxNS2ZqRWhITTR5aFJBTkNBQVM4ODllVDcwbFp1ZG9yLzlDK1pqSEtYcFJrMEo3bwpKcHFxeVpjOFRHeWlKVHg4YXhOdlJwZGRiNzRRdWQyWlV1OE8zUjJuWFBEam9uMWRVZDA1ZlNGVgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:39Z"
    name: hlf-tls-admin
    namespace: org-1
    resourceVersion: "1157044"
    uid: a9b1db2b-24e7-4a2b-addd-8c3a11aa454f
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyekNDQW9HZ0F3SUJBZ0lVTEZDOEYxWExmQVBrWVl4K3QwUGc5Z3dVekswd0NnWUlLb1pJemowRUF3SXcKYmpFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUkF3CkRnWURWUVFERXdkeVkyRlBjbWN4TUI0WERUSXlNREl5T0RFM05UZ3dNRm9YRFRJM01ESXlOekU0TURRd01Gb3cKV2pFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFTk1Bc0dBMVVFQ3hNRWNHVmxjakVOTUFzR0ExVUVBeE1FZFhObGNqQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQ29SOWFZTVJZMjlheDVDRmpsYnBnV2NCajkwdW5KY1VHN3oKWUd1NTJYeEdqQy83ajFoUVJoSVZySUUrNVNzYTZtdEpLV2ZiMCt3VTJ6MEhnNFdBNmUyamdnRVBNSUlCQ3pBTwpCZ05WSFE4QkFmOEVCQU1DQTZnd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHCkExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGUDFJTHhxTVYyNjFOZmhKM2JxRnpkUHZqR0p5TUI4R0ExVWQKSXdRWU1CYUFGSkhXWDBhakpTMlhaRnVKRlkvOUZQcHJBc1ZMTURVR0ExVWRFUVF1TUN5Q0NXeHZZMkZzYUc5egpkSUlaS2k1dmNtY3RNUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiSWNFZndBQUFUQlZCZ2dxQXdRRkJnY0lBUVJKCmV5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acGJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTYKSW5WelpYSWlMQ0pvWmk1VWVYQmxJam9pY0dWbGNpSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBNkJpbQpINTN2UlhqdEtBcHRsR2ozYXVpOW5Lc0E0Q3cvQ3hMQ0VkQWR2ZklDSUdkVXBGWXhOdE5PUjVXNDlOQnhEVU5lClU3eHVEV3VFT1EzeUo5SCtJek1KCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2c0V0pvR2NuZlR2YkFlQksKT3VTdGwzSGJyUnphT0l0UlRjc2VFd0paN1IyaFJBTkNBQVFxRWZXbURFV052V3NlUWhZNVc2WUZuQVkvZExweQpYRkJ1ODJCcnVkbDhSb3d2KzQ5WVVFWVNGYXlCUHVVckd1cHJTU2xuMjlQc0ZOczlCNE9GZ09udAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:46Z"
    name: hlf-tls-user
    namespace: org-1
    resourceVersion: "1157098"
    uid: 74d9ffc4-4711-4882-bda6-63c533a117ea
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    cacert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNLVENDQWMrZ0F3SUJBZ0lVUm5RWXpnNk5xcldFSTJzRlVpQUNZUTlWM1lJd0NnWUlLb1pJemowRUF3SXcKY1RFTE1Ba0dBMVVFQmhNQ1JsSXhHVEFYQmdOVkJBZ1RFRXh2YVhKbExVRjBiR0Z1ZEdseGRXVXhEekFOQmdOVgpCQWNUQms1aGJuUmxjekVRTUE0R0ExVUVDaE1IVTNWaWMzUnlZVEVQTUEwR0ExVUVDeE1HUm1GaWNtbGpNUk13CkVRWURWUVFERXdweVkyRlBjbVJsY21WeU1CNFhEVEl5TURJeU9ERTNOVGN3TUZvWERUTTNNREl5TkRFM05UY3cKTUZvd2NURUxNQWtHQTFVRUJoTUNSbEl4R1RBWEJnTlZCQWdURUV4dmFYSmxMVUYwYkdGdWRHbHhkV1V4RHpBTgpCZ05WQkFjVEJrNWhiblJsY3pFUU1BNEdBMVVFQ2hNSFUzVmljM1J5WVRFUE1BMEdBMVVFQ3hNR1JtRmljbWxqCk1STXdFUVlEVlFRREV3cHlZMkZQY21SbGNtVnlNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUKSUdUNnc3OS9oZ2JScVdVcU9OemU0WnRuY3BvWmdXTGZMSXFmUUF2dUp3ZUtCSnhCaUdOSGxISWZXVStKWExXcAo5Tk1Dcno3VVZUY2J3MDVsVDJpcy9hTkZNRU13RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJCk1BWUJBZjhDQVFFd0hRWURWUjBPQkJZRUZIU2JQNUNzU1R2MmdkN3MrYXBuWDFiK2RWWm9NQW9HQ0NxR1NNNDkKQkFNQ0EwZ0FNRVVDSVFEenNJRlJXQTdYd1MwMnNjdGZKNTVvWjNoeGRuMHpSZWMyOThROTdoOStMQUlnSitlUwpVemwzcFR5RFRJOHlMeG55VTRnWUpvZVNobmJPbWhuaWRDR2VzMGc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  kind: Secret
  metadata:
    creationTimestamp: "2022-02-28T18:03:32Z"
    name: ord-tls-rootcert
    namespace: org-1
    resourceVersion: "1156989"
    uid: 1f56b6fb-0d79-4227-a433-b5f211661fa3
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
