@startuml

skinparam shadowing false


package "Node B" as nodeB {
   rectangle "peer" as peerB {
    database ledgerB [
      ledger
      ----
      ----
    ]
  }
  rectangle "substrabac" as substrabacB {
    database localdbB [
      local db
      ----
      ----
    ]
    node server as djangoB
  }
  rectangle "Fabric CA" as fcaB {
    rectangle db as fcadbB {
        database usersB [
            users
            ----
            ----
        ]
        file {
            card USER_B
            card NODE_B_USER_A #PHYSICAL
        }
    }
    node server as fcaserverB
  }
}

actor client

USER_B -[hidden]r- NODE_B_USER_A

djangoB <-[#orange]> localdbB

fcaserverB <-[#orange]> usersB

client .> djangoB: credentials in cookies
client <.[#green]. djangoB

djangoB .> ledgerB
djangoB <.[#green]. ledgerB



@enduml
