@startuml

skinparam shadowing false


package "Node A" as nodeA {
  rectangle "peer" as peerA {
    database ledgerA [
      ledger
      ----
      ----
    ]
  }
  rectangle "substrabac" as substrabacA {
    database localdbA [
      local db
      ----
      ----
    ]
    node server as djangoA
  }
  rectangle "Fabric CA" as fcaA {
    rectangle db as fcadbA {
        database usersA [
            users
            ----
            ----
        ]
        file {
            card USER_A
            card NODE_A_USER_B
        }
    }
    node server as fcaserverA
  }
}

package "Node B" as nodeB {
   rectangle "peer" as peerB {
    database ledgerB [
      ledger
      ----
      ----
    ]
  }
  rectangle "substrabac" as substrabacB {
    database localdbB [
      local db
      ----
      ----
    ]
    node server as djangoB
  }
  rectangle "Fabric CA" as fcaB {
    rectangle db as fcadbB {
        database usersB [
            users
            ----
            ----
        ]
        file {
            card USER_B
            card NODE_B_USER_A #PHYSICAL
        }
    }
    node server as fcaserverB
  }
}

USER_A -[hidden]r- NODE_A_USER_B

djangoA <-[#orange]> localdbA
djangoB <-[#orange]> localdbB

fcaserverA <-[#orange]> usersA
fcaserverB <-[#orange]> usersB

NODE_B_USER_A .> djangoA : ask download for processing
NODE_B_USER_A <.[#green]u. djangoA : get asset

djangoA .> ledgerA: " " "\nask own ledger \n for asset \n and get its\n permissions\n\n"
djangoA <.[#green]u. ledgerA


@enduml
