@startuml

skinparam shadowing false

autonumber

participant "server Node A" as serverA
participant "Fabric CA A" as fcaA
database "Fabric CA A database" as dbA

[-> serverA
activate serverA #FFBBBB

serverA -[#green]> fcaA: enroll username/password
activate fcaA #FFBBBB


fcaA -[#green]> dbA: get user
activate dbA #FFBBBB
fcaA <[#blue]-- dbA
deactivate dbA

serverA <[#blue]-- fcaA: enrollment object
deactivate fcaA

serverA -> serverA: compute hashed modulus

serverA -> serverA: check if InternalUser\nwith permission in asset\npermissions\nand related modulus

[<- serverA

deactivate serverA

@enduml
