{{- if index .Values "hlf-peer" "enabled" }}
{{- range  .Values.chaincodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "substra.fullname" $ }}-chaincode-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-chaincode
    app.kubernetes.io/part-of: {{ template "substra.name" $ }}
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ template "substra.name" $ }}-chaincode-{{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "substra.name" $ }}-chaincode-{{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
        - name: substra-chaincode-{{ .name }}
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: "{{ .image.pullPolicy }}"
          command: ['./chaincode']
          env:
            - name: CHAINCODE_CCID
              valueFrom:
                secretKeyRef:
                  name: chaincode-ccid-{{ .name }}
                  key: ccid
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:{{ .port }}"
            - name: TLS_CERT_FILE
              value: "/var/hyperledger/tls/client/pair/tls.crt"
            - name: TLS_KEY_FILE
              value: "/var/hyperledger/tls/client/pair/tls.key"
            - name: TLS_ROOTCERT_FILE
              value: "/var/hyperledger/tls/client/cert/cacert.pem"
          volumeMounts:
            - mountPath: /var/hyperledger/tls/client/pair
              name: tls-client
            - mountPath: /var/hyperledger/tls/client/cert
              name: tls-clientrootcert
          ports:
            - containerPort: {{ .port }}
      volumes:
      - name: tls-client
        secret:
          secretName: {{ $.Values.secrets.tlsClient }}
      - name: tls-clientrootcert
        secret:
          secretName: {{ $.Values.secrets.tlsClientRootCert }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "substra.fullname" $ }}-chaincode-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-chaincode-{{ .name }}
spec:
  type: ClusterIP
  ports:
  - name: chaincode
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .port }}
  selector:
    app.kubernetes.io/name: {{ template "substra.name" $ }}-chaincode-{{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
