{{- if .Values.applicationChannelOperator.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "substra.fullname" . }}-appchannel-operator
  labels:
    app.kubernetes.io/name: {{ template "substra.fullname" . }}-appchannel-operator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.applicationChannelOperator.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.applicationChannelOperator.ingress.tls }}
  tls:
  {{- range .Values.applicationChannelOperator.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range  .Values.applicationChannelOperator.ingress.hosts  }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ template "substra.fullname" $ }}-appchannel-operator
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
---
