# Copyright 2018 Owkin, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and (index .Values "hlf-peer" "enabled") (.Values.hooks.uninstallChaincode.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "substra.fullname" . }}-hook-uninstall-chaincode
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.name" . }}-hook-uninstall-chaincode
    app.kubernetes.io/part-of: {{ template "substra.name" . }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "substra.fullname" . }}
      containers:
        - name: main
          image: docker
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ['sh', '-c']
          args:
            - |
            {{- range .Values.chaincodes }}
              docker rm -f nid1-{{ $.Release.Name }}-{{ .name }}-{{ .version }} || true
              docker rmi -f $(docker images -q 'nid1-{{ $.Release.Name }}-{{ .name }}-{{ .version }}*') || true
            {{- end }}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: dockersocket
      volumes:
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
