apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "substra.fullname" . }}-couchdb-credentials
data:
  COUCHDB_USER: {{ index .Values "hlf-couchdb" "couchdbUsername" | b64enc }}
  COUCHDB_PASSWORD: {{ index .Values "hlf-couchdb" "couchdbPassword" | b64enc }}
