apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "substra.fullname" . }}-couchdb-credentials
data:
  COUCHDB_USER: {{ index .Values "couchdb" "adminUsername" | b64enc }}
  COUCHDB_PASSWORD: {{ index .Values "couchdb" "adminPassword" | b64enc }}
