# Copyright 2018 Owkin, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ABOUT
#
#   This is An hlf-k8s deployment with 4 organizations using the default
#   application channel policy ("MAJORITY")
#
---
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: substrafoundation/hlf-k8s
      context: .
      docker:
        dockerfile: images/hlf-k8s/Dockerfile
      sync:
        manual:
          - src: ./bin/*
            dest: /usr/local/bin/

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: network-orderer
        chartPath: charts/hlf-k8s
        namespace: orderer
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s
        setValues:
          nginx-ingress.enabled: true
          hlf-peer.enabled: false
          hlf-ca.caName: rcaOrderer
          hlf-ca.host: network-orderer-hlf-ca.orderer
          hlf-ca.orderer.host: network-orderer-hlf-ca.orderer
          organization.id: MyOrdererMSP
          organization.name: MyOrderer
          hlf-ord.enabled: true
          hlf-ord.monitor.enabled: true
          # Add Org to system channel to allows them to adminstrate application channels
          systemChannel.organizations[0].org: MyOrg1
          systemChannel.organizations[0].mspid: MyOrg1MSP
          systemChannel.organizations[0].configUrl: network-org-1-peer-1-hlf-k8s-config-operator.org-1/config/configOrg.json
          systemChannel.organizations[1].org: MyOrg2
          systemChannel.organizations[1].mspid: MyOrg2MSP
          systemChannel.organizations[1].configUrl: network-org-2-peer-1-hlf-k8s-config-operator.org-2/config/configOrg.json
          systemChannel.organizations[2].org: MyOrg3
          systemChannel.organizations[2].mspid: MyOrg3MSP
          systemChannel.organizations[2].configUrl: network-org-3-peer-1-hlf-k8s-config-operator.org-3/config/configOrg.json
          systemChannel.organizations[3].org: MyOrg4
          systemChannel.organizations[3].mspid: MyOrg4MSP
          systemChannel.organizations[3].configUrl: network-org-3-peer-1-hlf-k8s-config-operator.org-3/config/configOrg.json
          hlf-ord.host: network-orderer-hlf-ord.orderer
          hlf-ord.ord.mspID: MyOrdererMSP
          enrollments.creds[0].name: admin
          enrollments.creds[0].secret: adminpwd
          enrollments.creds[0].options: "--id.attrs admin=true:ecert"
          enrollments.creds[1].name: user
          enrollments.creds[1].secret: pwd
          enrollments.creds[1].options: "--id.type orderer"
          enrollments.csrHost: network-orderer-hlf-ord.orderer
          toolbox.enabled: true
          hooks.serviceAccount.name: substra-delete-hook

      - name: network-org-1-peer-1
        chartPath: charts/hlf-k8s
        namespace: org-1
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s
        setValues:
          nginx-ingress.enabled: true
          nginx-ingress.controller.scope.enabled: true
          hlf-ca.caName: rcaOrg1
          hlf-ca.host: network-org-1-peer-1-hlf-ca.org-1
          hlf-ca.orderer.host: network-orderer-hlf-ca.orderer
          hlf-peer.host: network-org-1-peer-1-hlf-peer.org-1
          organization.id: MyOrg1MSP
          organization.name: MyOrg1
          hlf-peer.peer.mspID: MyOrg1MSP
          chaincodes[0].name: mycc
          chaincodes[0].version: "1.0"
          chaincodes[0].src: https://github.com/SubstraFoundation/substra-chaincode/archive/master.tar.gz
          appChannels[0].channelName: mychannel
          appChannels[0].organizations[0].org: MyOrg1
          appChannels[0].organizations[0].mspid: MyOrg1MSP
          appChannels[0].organizations[0].configUrl: network-org-1-peer-1-hlf-k8s-config-operator.org-1/config/configOrgWithAnchors.json
          appChannels[0].organizations[1].org: MyOrg2
          appChannels[0].organizations[1].mspid: MyOrg2MSP
          appChannels[0].organizations[1].configUrl: network-org-2-peer-1-hlf-k8s-config-operator.org-2/config/configOrgWithAnchors.json
          appChannels[0].organizations[2].org: MyOrg3
          appChannels[0].organizations[2].mspid: MyOrg3MSP
          appChannels[0].organizations[2].configUrl: network-org-3-peer-1-hlf-k8s-config-operator.org-3/config/configOrgWithAnchors.json
          appChannels[0].organizations[3].org: MyOrg4
          appChannels[0].organizations[3].mspid: MyOrg4MSP
          appChannels[0].organizations[3].configUrl: network-org-4-peer-1-hlf-k8s-config-operator.org-4/config/configOrgWithAnchors.json
          appChannels[0].proposalOrganizations[0].org: MyOrg1
          appChannels[0].proposalOrganizations[0].mspid: MyOrg1MSP
          appChannels[0].proposalOrganizations[0].proposalServerUrl: network-org-1-peer-1-hlf-k8s-appchannel-operator.org-1/proposal/
          appChannels[0].proposalOrganizations[1].org: MyOrg2
          appChannels[0].proposalOrganizations[1].mspid: MyOrg2MSP
          appChannels[0].proposalOrganizations[1].proposalServerUrl: network-org-2-peer-1-hlf-k8s-appchannel-operator.org-2/proposal/
          appChannels[0].proposalOrganizations[2].org: MyOrg3
          appChannels[0].proposalOrganizations[2].mspid: MyOrg3MSP
          appChannels[0].proposalOrganizations[2].proposalServerUrl: network-org-3-peer-1-hlf-k8s-appchannel-operator.org-3/proposal/
          appChannels[0].proposalOrganizations[3].org: MyOrg4
          appChannels[0].proposalOrganizations[3].mspid: MyOrg4MSP
          appChannels[0].proposalOrganizations[3].proposalServerUrl: network-org-4-peer-1-hlf-k8s-appchannel-operator.org-4/proposal/
          # appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member')
          appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member'\,'MyOrg3MSP.member'\,'MyOrg4MSP.member')
          appChannels[0].chaincodeName: mycc
          appChannels[0].chaincodeVersion: "1.0"
          hlf-ord.host: network-orderer-hlf-ord.orderer
          hlf-peer.peer.gossip.externalEndpoint: network-org-1-peer-1-hlf-peer.org-1:7051
          enrollments.creds[0].name: admin
          enrollments.creds[0].secret: adminpwd
          enrollments.creds[0].options: "--id.attrs hf.Registrar.Roles=client,hf.Registrar.Attributes=*,hf.Revoker=true,hf.GenCRL=true,admin=true:ecert,abac.init=true:ecert"
          enrollments.creds[1].name: user,
          enrollments.creds[1].secret: pwd,
          enrollments.creds[1].options: "--id.type peer"
          enrollments.csrHost: network-org-1-peer-1-hlf-peer.org-1
          toolbox.enabled: true
          hooks.serviceAccount.name: substra-delete-hook

      - name: network-org-2-peer-1
        chartPath: charts/hlf-k8s
        namespace: org-2
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s
        setValues:
          nginx-ingress.enabled: true
          nginx-ingress.controller.scope.enabled: true
          hlf-ca.caName: rcaOrg2
          hlf-ca.host: network-org-2-peer-1-hlf-ca.org-2
          hlf-ca.orderer.host: network-orderer-hlf-ca.orderer
          hlf-peer.host: network-org-2-peer-1-hlf-peer.org-2
          organization.id: MyOrg2MSP
          organization.name: MyOrg2
          hlf-peer.peer.mspID: MyOrg2MSP
          chaincodes[0].name: mycc
          chaincodes[0].version: "1.0"
          chaincodes[0].src: https://github.com/SubstraFoundation/substra-chaincode/archive/master.tar.gz
          appChannels[0].channelName: mychannel
          appChannels[0].organizations[0].org: MyOrg1
          appChannels[0].organizations[0].mspid: MyOrg1MSP
          appChannels[0].organizations[0].configUrl: network-org-1-peer-1-hlf-k8s-config-operator.org-1/config/configOrgWithAnchors.json
          appChannels[0].organizations[1].org: MyOrg2
          appChannels[0].organizations[1].mspid: MyOrg2MSP
          appChannels[0].organizations[1].configUrl: network-org-2-peer-1-hlf-k8s-config-operator.org-2/config/configOrgWithAnchors.json
          appChannels[0].organizations[2].org: MyOrg3
          appChannels[0].organizations[2].mspid: MyOrg3MSP
          appChannels[0].organizations[2].configUrl: network-org-3-peer-1-hlf-k8s-config-operator.org-3/config/configOrgWithAnchors.json
          appChannels[0].organizations[3].org: MyOrg4
          appChannels[0].organizations[3].mspid: MyOrg4MSP
          appChannels[0].organizations[3].configUrl: network-org-4-peer-1-hlf-k8s-config-operator.org-4/config/configOrgWithAnchors.json
          appChannels[0].proposalOrganizations[0].org: MyOrg1
          appChannels[0].proposalOrganizations[0].mspid: MyOrg1MSP
          appChannels[0].proposalOrganizations[0].proposalServerUrl: network-org-1-peer-1-hlf-k8s-appchannel-operator.org-1/proposal/
          appChannels[0].proposalOrganizations[1].org: MyOrg2
          appChannels[0].proposalOrganizations[1].mspid: MyOrg2MSP
          appChannels[0].proposalOrganizations[1].proposalServerUrl: network-org-2-peer-1-hlf-k8s-appchannel-operator.org-2/proposal/
          appChannels[0].proposalOrganizations[2].org: MyOrg3
          appChannels[0].proposalOrganizations[2].mspid: MyOrg3MSP
          appChannels[0].proposalOrganizations[2].proposalServerUrl: network-org-3-peer-1-hlf-k8s-appchannel-operator.org-3/proposal/
          appChannels[0].proposalOrganizations[3].org: MyOrg4
          appChannels[0].proposalOrganizations[3].mspid: MyOrg4MSP
          appChannels[0].proposalOrganizations[3].proposalServerUrl: network-org-4-peer-1-hlf-k8s-appchannel-operator.org-4/proposal/
          # appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member')
          appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member'\,'MyOrg3MSP.member'\,'MyOrg4MSP.member')
          appChannels[0].chaincodeName: mycc
          appChannels[0].chaincodeVersion: "1.0"
          hlf-ord.host: network-orderer-hlf-ord.orderer
          hlf-peer.peer.gossip.externalEndpoint: network-org-2-peer-1-hlf-peer.org-2:7051
          enrollments.creds[0].name: admin
          enrollments.creds[0].secret: adminpwd
          enrollments.creds[0].options: "--id.attrs hf.Registrar.Roles=client,hf.Registrar.Attributes=*,hf.Revoker=true,hf.GenCRL=true,admin=true:ecert,abac.init=true:ecert"
          enrollments.creds[1].name: user,
          enrollments.creds[1].secret: pwd,
          enrollments.creds[1].options: "--id.type peer"
          enrollments.csrHost: network-org-2-peer-1-hlf-peer.org-2
          toolbox.enabled: true
          hooks.serviceAccount.name: substra-delete-hook

      - name: network-org-3-peer-1
        chartPath: charts/hlf-k8s
        namespace: org-3
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s
        setValues:
          nginx-ingress.enabled: true
          nginx-ingress.controller.scope.enabled: true
          hlf-ca.caName: rcaOrg3
          hlf-ca.host: network-org-3-peer-1-hlf-ca.org-3
          hlf-ca.orderer.host: network-orderer-hlf-ca.orderer
          hlf-peer.host: network-org-3-peer-1-hlf-peer.org-3
          organization.id: MyOrg3MSP
          organization.name: MyOrg3
          hlf-peer.peer.mspID: MyOrg3MSP
          chaincodes[0].name: mycc
          chaincodes[0].version: "1.0"
          chaincodes[0].src: https://github.com/SubstraFoundation/substra-chaincode/archive/master.tar.gz
          appChannels[0].channelName: mychannel
          appChannels[0].organizations[0].org: MyOrg1
          appChannels[0].organizations[0].mspid: MyOrg1MSP
          appChannels[0].organizations[0].configUrl: network-org-1-peer-1-hlf-k8s-config-operator.org-1/config/configOrgWithAnchors.json
          appChannels[0].organizations[1].org: MyOrg2
          appChannels[0].organizations[1].mspid: MyOrg2MSP
          appChannels[0].organizations[1].configUrl: network-org-2-peer-1-hlf-k8s-config-operator.org-2/config/configOrgWithAnchors.json
          appChannels[0].organizations[2].org: MyOrg3
          appChannels[0].organizations[2].mspid: MyOrg3MSP
          appChannels[0].organizations[2].configUrl: network-org-3-peer-1-hlf-k8s-config-operator.org-3/config/configOrgWithAnchors.json
          appChannels[0].organizations[3].org: MyOrg4
          appChannels[0].organizations[3].mspid: MyOrg4MSP
          appChannels[0].organizations[3].configUrl: network-org-4-peer-1-hlf-k8s-config-operator.org-4/config/configOrgWithAnchors.json
          appChannels[0].proposalOrganizations[0].org: MyOrg1
          appChannels[0].proposalOrganizations[0].mspid: MyOrg1MSP
          appChannels[0].proposalOrganizations[0].proposalServerUrl: network-org-1-peer-1-hlf-k8s-appchannel-operator.org-1/proposal/
          appChannels[0].proposalOrganizations[1].org: MyOrg2
          appChannels[0].proposalOrganizations[1].mspid: MyOrg2MSP
          appChannels[0].proposalOrganizations[1].proposalServerUrl: network-org-2-peer-1-hlf-k8s-appchannel-operator.org-2/proposal/
          appChannels[0].proposalOrganizations[2].org: MyOrg3
          appChannels[0].proposalOrganizations[2].mspid: MyOrg3MSP
          appChannels[0].proposalOrganizations[2].proposalServerUrl: network-org-3-peer-1-hlf-k8s-appchannel-operator.org-3/proposal/
          appChannels[0].proposalOrganizations[3].org: MyOrg4
          appChannels[0].proposalOrganizations[3].mspid: MyOrg4MSP
          appChannels[0].proposalOrganizations[3].proposalServerUrl: network-org-4-peer-1-hlf-k8s-appchannel-operator.org-4/proposal/
          # appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member')
          appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member'\,'MyOrg3MSP.member'\,'MyOrg4MSP.member')
          appChannels[0].chaincodeName: mycc
          appChannels[0].chaincodeVersion: "1.0"
          hlf-ord.host: network-orderer-hlf-ord.orderer
          hlf-peer.peer.gossip.externalEndpoint: network-org-3-peer-1-hlf-peer.org-3:7051
          enrollments.creds[0].name: admin
          enrollments.creds[0].secret: adminpwd
          enrollments.creds[0].options: "--id.attrs hf.Registrar.Roles=client,hf.Registrar.Attributes=*,hf.Revoker=true,hf.GenCRL=true,admin=true:ecert,abac.init=true:ecert"
          enrollments.creds[1].name: user,
          enrollments.creds[1].secret: pwd,
          enrollments.creds[1].options: "--id.type peer"
          enrollments.csrHost: network-org-3-peer-1-hlf-peer.org-3
          toolbox.enabled: true
          hooks.serviceAccount.name: substra-delete-hook

      - name: network-org-4-peer-1
        chartPath: charts/hlf-k8s
        namespace: org-4
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s
        setValues:
          nginx-ingress.enabled: true
          nginx-ingress.controller.scope.enabled: true
          hlf-ca.caName: rcaOrg4
          hlf-ca.host: network-org-4-peer-1-hlf-ca.org-4
          hlf-ca.orderer.host: network-orderer-hlf-ca.orderer
          hlf-peer.host: network-org-4-peer-1-hlf-peer.org-4
          organization.id: MyOrg4MSP
          organization.name: MyOrg4
          hlf-peer.peer.mspID: MyOrg4MSP
          chaincodes[0].name: mycc
          chaincodes[0].version: "1.0"
          chaincodes[0].src: https://github.com/SubstraFoundation/substra-chaincode/archive/master.tar.gz
          appChannels[0].channelName: mychannel
          appChannels[0].organizations[0].org: MyOrg1
          appChannels[0].organizations[0].mspid: MyOrg1MSP
          appChannels[0].organizations[0].configUrl: network-org-1-peer-1-hlf-k8s-config-operator.org-1/config/configOrgWithAnchors.json
          appChannels[0].organizations[1].org: MyOrg2
          appChannels[0].organizations[1].mspid: MyOrg2MSP
          appChannels[0].organizations[1].configUrl: network-org-2-peer-1-hlf-k8s-config-operator.org-2/config/configOrgWithAnchors.json
          appChannels[0].organizations[2].org: MyOrg3
          appChannels[0].organizations[2].mspid: MyOrg3MSP
          appChannels[0].organizations[2].configUrl: network-org-3-peer-1-hlf-k8s-config-operator.org-3/config/configOrgWithAnchors.json
          appChannels[0].organizations[3].org: MyOrg4
          appChannels[0].organizations[3].mspid: MyOrg4MSP
          appChannels[0].organizations[3].configUrl: network-org-4-peer-1-hlf-k8s-config-operator.org-4/config/configOrgWithAnchors.json
          appChannels[0].proposalOrganizations[0].org: MyOrg1
          appChannels[0].proposalOrganizations[0].mspid: MyOrg1MSP
          appChannels[0].proposalOrganizations[0].proposalServerUrl: network-org-1-peer-1-hlf-k8s-appchannel-operator.org-1/proposal/
          appChannels[0].proposalOrganizations[1].org: MyOrg2
          appChannels[0].proposalOrganizations[1].mspid: MyOrg2MSP
          appChannels[0].proposalOrganizations[1].proposalServerUrl: network-org-2-peer-1-hlf-k8s-appchannel-operator.org-2/proposal/
          appChannels[0].proposalOrganizations[2].org: MyOrg3
          appChannels[0].proposalOrganizations[2].mspid: MyOrg3MSP
          appChannels[0].proposalOrganizations[2].proposalServerUrl: network-org-3-peer-1-hlf-k8s-appchannel-operator.org-3/proposal/
          appChannels[0].proposalOrganizations[3].org: MyOrg4
          appChannels[0].proposalOrganizations[3].mspid: MyOrg4MSP
          appChannels[0].proposalOrganizations[3].proposalServerUrl: network-org-4-peer-1-hlf-k8s-appchannel-operator.org-4/proposal/
          # appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member')
          appChannels[0].chaincodePolicy: OR('MyOrg1MSP.member'\,'MyOrg2MSP.member'\,'MyOrg3MSP.member'\,'MyOrg4MSP.member')
          appChannels[0].chaincodeName: mycc
          appChannels[0].chaincodeVersion: "1.0"
          hlf-ord.host: network-orderer-hlf-ord.orderer
          hlf-peer.peer.gossip.externalEndpoint: network-org-4-peer-1-hlf-peer.org-4:7051
          enrollments.creds[0].name: admin
          enrollments.creds[0].secret: adminpwd
          enrollments.creds[0].options: "--id.attrs hf.Registrar.Roles=client,hf.Registrar.Attributes=*,hf.Revoker=true,hf.GenCRL=true,admin=true:ecert,abac.init=true:ecert"
          enrollments.creds[1].name: user,
          enrollments.creds[1].secret: pwd,
          enrollments.creds[1].options: "--id.type peer"
          enrollments.csrHost: network-org-4-peer-1-hlf-peer.org-4
          toolbox.enabled: true
          hooks.serviceAccount.name: substra-delete-hook
    flags:
      install: ["--create-namespace"]
  kubectl:
    manifests:
      - k8s/serviceAccount-orderer.yaml
      - k8s/serviceAccount-org-1.yaml
      - k8s/serviceAccount-org-2.yaml
      - tools/k8s/serviceAccount-org-3.yaml
      - tools/k8s/serviceAccount-org-4.yaml
