# Copyright 2018 Owkin, inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: substrafoundation/hlf-k8s
      context: ../../
      docker:
        dockerfile: images/hlf-k8s/Dockerfile
      sync:
        manual:
          - src: ./bin/*
            dest: /usr/local/bin/

deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: network-orderer
        chartPath: ../../charts/hlf-k8s
        namespace: orderer
        valuesFiles: [values/orderer.yaml]
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s

      - name: network-org-1-peer-1
        chartPath: ../../charts/hlf-k8s
        namespace: org-1
        valuesFiles: [values/org-1-peer-1.yaml]
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s


      - name: network-org-2-peer-1
        chartPath: ../../charts/hlf-k8s
        namespace: org-2
        valuesFiles: [values/org-2-peer-1.yaml]
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/hlf-k8s

    flags:
      install: ["--create-namespace"]


  kubectl:
    manifests:
      - examples/secrets/secrets-orderer-genesis.yaml
      - examples/secrets/secrets-orderer.yaml
      - examples/secrets/secrets-org-1.yaml
      - examples/secrets/secrets-org-2.yaml

