@startuml

skinparam shadowing false


package "Node A" as nodeA {
   rectangle "peer" as peerA {
    database ledgerA [
      ledger
      ----
      ----
    ]
  }
  rectangle "substrabac" as substrabacA {
    database localdbA [
      local db
      ----
      USER_A1
      ----
    ]
    node server as djangoA
  }
  rectangle "Fabric CA" as fcaA {
    rectangle db as fcadbA {
        database usersA [
            users
            ----
            ----
        ]
        file {
            card USER_A
            card NODE_A_USER_B
        }
    }
    node server as fcaserverA
  }
}

package "Node B" as nodeB {
   rectangle "peer" as peerB {
    database ledgerB [
      ledger
      ----
      ----
    ]
  }
  rectangle "substrabac" as substrabacB {
    database localdbB [
      local db
      ----
      ----
    ]
    node server as djangoB
  }
  rectangle "Fabric CA" as fcaB {
    rectangle db as fcadbB {
        database usersB [
            users
            ----
            ----
        ]
        file {
            card USER_B
            card NODE_B_USER_A #PHYSICAL
        }
    }
    node server as fcaserverB
  }
}

actor "client from Node A\n USER_A1" as client

nodeA -[hidden]-> nodeB

USER_B -[hidden]r- NODE_B_USER_A
USER_A -[hidden]r- NODE_A_USER_B

djangoB <-[#orange]> localdbB
djangoA <-[#orange]> localdbA

fcaserverB <-[#orange]> usersB
fcaserverA <-[#orange]> usersA

client .> djangoA: "credentials in\nsession_id\nfrom login"
client <.[#green]. djangoA

djangoA .> djangoB: use credentials from Node A (NODE_B_USER_A)
djangoA <.[#green]. djangoB

djangoB .> ledgerB
djangoB <.[#green]. ledgerB



@enduml
