@startuml

skinparam shadowing false

autonumber

actor "USER_A1" as client
participant "server Node A" as serverA
database "local db A" as dbA
participant "server Node B" as serverB
participant "ledger B" as ledger
database "local db B" as dbB

client -[#green]> serverA: cookie (session_id)\n+ url in GET\non /download
activate serverA #FFBBBB

serverA -[#green]> dbA: check user\nbelongs to\nnode A
activate dbA #FFBBBB
serverA <[#blue]-- dbA
deactivate dbA

rnote over serverA: precheck permissions\nby asking asset on ledger A.\nnode know its own related\npermission

client <--X serverA: permissions\ninvalid

serverA -[#green]> serverB: credentials\nas cookies\n(username/password)
activate serverB #FFBBBB

serverB -[#green]> ledger: ask asset
activate ledger #FFBBBB
serverB <[#blue]-- ledger: send asset or raise
deactivate ledger
rnote over serverB: check permission:\n- enroll user on fabric-ca \n with username/password\n- get enrollement cert\n- compute hashed modulus\n- check if internal user with\n right permission is\n related to this modulus
serverB -[#green]> dbB: ask object
activate dbB #FFBBBB
serverB <[#blue]-- dbB: send object or raise
deactivate dbB


serverA <[#blue]-- serverB: content of\nfile or exception
deactivate serverB

client <[#blue]-- serverA: content of\nfile or exception

deactivate serverA

@enduml
