@startuml

skinparam shadowing false

autonumber

participant "server Node A" as serverA
database "ledger A" as ledgerA

[-> serverA
activate serverA #FFBBBB

serverA -[#green]> ledgerA: ask asset by\nextracting id from url
activate ledgerA #FFBBBB
serverA <[#blue]-- ledgerA
deactivate ledgerA


serverA -> serverA: check if InternalUser\nwith permission in asset permissions

[<- serverA

deactivate serverA

@enduml
