---
name: Publish docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'
env:
  REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      matrix:
        docker-image: [fabric-peer, fabric-tools]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
        fi

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: '${{ env.REGISTRY }}/substra/${{matrix.docker-image}}'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./docker/${{ matrix.docker-image }}/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
