---
name: Publish image on GCR
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        docker-image: [fabric-peer, fabric-tools]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "LATEST=true" >> $GITHUB_ENV
          echo "LATEST is set to true"
        else
          echo "LATEST=false" >> $GITHUB_ENV
          echo "LATEST is set to false"
        fi

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Docker metadata
      id: docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{matrix.docker-image}}'
        flavor: |
          latest=${{ env.LATEST }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./docker/${{ matrix.docker-image }}/Dockerfile
        context: .
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
