name: Helm

on:
  push:
    branches:
      - "master"
    paths:
      - "charts/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "charts/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: "v3.5.0"
        id: install
      - name: Install tools
        run: |
          sudo snap install yq
      - name: Build dependencies
        run: helm dep update charts/hlf-k8s
      - name: Lint Chart
        run: helm lint charts/hlf-k8s
      - name: Validate version increment
        env:
          HARBOR_AUTH_TOKEN: ${{ secrets.HARBOR_AUTH_TOKEN }}
          HARBOR_AUTH_USER: "robot$connect-hlf-k8s+connect-hlf-k8s-pusher"
        run: |
          helm repo add --username=$HARBOR_AUTH_USER --password=$HARBOR_AUTH_TOKEN owkin-priv https://core.harbor.tooling.owkin.com/chartrepo/connect-hlf-k8s
          RES=$(helm search repo owkin-priv/hlf-k8s --version $(yq eval .version charts/hlf-k8s/Chart.yaml))
          if [ "${RES}" == "No results found" ]; then
            echo "Version incremented"
          else
            echo "Validation failed, you should upgrade the chart version in Chart.yaml"
            exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
        with:
          version: "v3.5.0"
        id: install
      - name: Install tools
        run: |
          sudo snap install yq
          helm plugin install https://github.com/chartmuseum/helm-push
      - name: Package chart
        env:
          HARBOR_AUTH_TOKEN: ${{ secrets.HARBOR_AUTH_TOKEN }}
          HARBOR_AUTH_USER: "robot$connect-hlf-k8s+connect-hlf-k8s-pusher"
        run: |
          helm repo add owkin https://owkin.github.io/charts/
          helm dep build charts/hlf-k8s
          helm package charts/hlf-k8s
          helm repo add --username=$HARBOR_AUTH_USER --password=$HARBOR_AUTH_TOKEN owkin-priv https://core.harbor.tooling.owkin.com/chartrepo/connect-hlf-k8s
          helm cm-push hlf-k8s-$(yq eval .version charts/hlf-k8s/Chart.yaml).tgz owkin-priv
