name: Helm

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3.5
        with:
          version: "v3.5.0"
        id: install
      - name: Install tools
        run: |
          sudo snap install yq
      - name: Build dependencies
        run: helm dep update charts/hlf-k8s
      - name: Lint Chart
        run: helm lint charts/hlf-k8s
      - name: Validate version increment
        run: |
          helm repo add substra https://substra.github.io/charts
          RES=$(helm search repo substra/hlf-k8s --version $(yq eval .version charts/hlf-k8s/Chart.yaml))
          if [ "${RES}" == "No results found" ]; then
            echo "Version incremented"
          else
            echo "Validation failed, you should upgrade the chart version in Chart.yaml"
            exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v3.5
        with:
          version: "v3.5.0"
        id: install

      - name: Package chart
        run: |
          helm repo add owkin https://owkin.github.io/charts/
          helm repo add couchdb https://apache.github.io/couchdb-helm
          helm dep build charts/hlf-k8s
          helm package charts/hlf-k8s

      - name: Clone Substra charts
        uses: actions/checkout@v4
        with:
          repository: Substra/charts
          ref: 'main'
          token: ${{ secrets.CHARTS_GITHUB_TOKEN }}
          path: substra-charts

      - name: Publish chart
        run: |
          mv hlf-k8s-$(grep -e "^version" charts/hlf-k8s/Chart.yaml | cut -c10-).tgz substra-charts/
          cd substra-charts
          helm repo index .
          git add .
          git config --global user.email "gh-actions@github.com"
          git config --global user.name "GitHub Action"
          git commit -s --message "GitHub Action: ${{ github.repository }}@${{ github.sha }}"
          git push --quiet --set-upstream origin main
